name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
      - testing
      - release
      - bugfix
      - feature
  pull_request:
    branches:
      - main
      - develop
      - testing
      - release
      - bugfix
      - feature

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Gradle
      run: ./gradlew build

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Run tests with Gradle
      run: ./gradlew test

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Deploy to Production
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: ./deploy.sh
